### ISSUE TITLE
Charge method - see how the customer has payed

### ISSUE THREAD

**Issue by webprogrammierer** [amzn/amazon-pay-sdk-php#41]
How can I see which charge method the customer selected to buy my product/service?

I want to see it in my seller central.
And are there any API functions calls to find you which charge method the customer used?

I want to find out how many customer pay with creditcard (and which creditcard: mastercard, Visa, ...) and how many pay with direct debit / debit transfair.

Thank you.

**Comment by islandskater43** [comment]
The details around the charge method selected are not available through Amazon Pay. If you have further questions, feel free to reopen.
