### ISSUE TITLE
Cannot get /user/profile in v3.0.0

### ISSUE THREAD

**Issue by pdbreen** [amzn/amazon-pay-sdk-php#43]
Authorization: bearer header added by HttpCurl::httpGet()  is overwritten by HttpCurl::execute() method.  As a result, attempts to get /user/profile detail end of with a 400 / malformed request result.

Pull request to follow.

**Comment by bjguillot** [comment]
Thanks for your contribution.  We are reviewing your pull request.

**Comment by bjguillot** [comment]
Merged the PR back in 2017 but never closed out the issue issue.  This was incorporated in version 3.1.0 back in May 2017.
