### ISSUE TITLE
Get Billing Address after Authorization/Capture?

### ISSUE THREAD

**Issue by dvnkshl** [amzn/amazon-pay-sdk-php#66]
Is it possible to collect the billing address after authorization/capture? Needed for tax purposes.

**Comment by mglaman** [comment]
Yes, but only if you're in the UK region, I believe. Maybe EU as well.

**Comment by islandskater43** [comment]
Correct for the most part - @dvnkshl - can you reach out to merchant support? They'll be able to assist you. https://pay.amazon.com/contact

If after connecting with them you still need support, please reopen this issue.
