### ISSUE TITLE
Can't settle in a production environment

### ISSUE THREAD

**Issue by SatoshiSakakibara** [amzn/amazon-pay-sdk-php#76]
Possible in a test environment, why?

I make three payment site.
It is a system to settle the product of different price to each.

When I tried it in the test environment, the sales were created without any problem.
However, when I replaced the widget .js with the one in the production environment, that was not done.

Why is this happening?
The structure is such that the payment information is passed from the payment site through the shipping address and payment information widget, and through the file checkout.php.

The code described on this page is for reference when creating.
https://qiita.com/arawow/items/8d9b4b5434a48332b246

Please help me.
To the end, thank you for keeping in touch with the Japanese ugly English.

**Comment by bjguillot** [comment]
What error messages were you seeing when moving to the production environment?

Changing the Widgets.js file to production is one piece that needs to happen.  You also need to be sure that you are sending 'sandbox' => false as part of the config that gets sent to the Client.

**Comment by SatoshiSakakibara** [comment]
Thanks answerd.

Your proposal was correct, but the payment didn't go wrong.
As you said, I found that the sandbox parameter in Client.php is true and changed it to false.
It seems to work well to a certain extent, but it seems that it is not working well when handing the charge to the seller.
That's because php's error message doesn't come up, and it changes to the payment failure page that I set up.( https://hand-school.com/paymenterror )

https://hand-school.com/payment4.html ←This is the page where you installed the button widget.

---Here is the php code for widget display---
<?php
    session_start();
    //アクセストークンをセッションに保存しておく
    $_SESSION['access_token'] = $_GET['access_token'];
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
content="width=device-width,initial-scale=1.0, maximum-scale=1.0"/>
<title>Amazonpayご住所、お支払い情報の選択</title>
</head>

<body>
	<script type="text/javascript">
    document.getElementById('Logout').onclick = function() {
        amazon.Login.logout();
    };
</script>

<div id="addressBookWidgetDiv" style="width:300px; height:240px;"></div>

<div id="walletWidgetDiv" style="width:300px; height:240px;"></div>
<script>
    window.onAmazonLoginReady = function() {
        amazon.Login.setClientId('---myClientid---');
    };
</script>
<script src='https://static-fe.payments-amazon.com/OffAmazonPayments/jp/lpa/js/Widgets.js'></script>
<script type="text/javascript">

    window.onAmazonPaymentsReady = function() {
      showAddressBookWidget();
  };
    function showAddressBookWidget() {
        new OffAmazonPayments.Widgets.AddressBook({
          sellerId: '---mysellerid---',

          onReady: function (orderReference) {
              var orderReferenceId = orderReference.getAmazonOrderReferenceId();
              var el;
              if ((el = document.getElementById("orderReferenceId"))) {
                el.value = orderReferenceId;
              }
              //アドレス帳ウィジェット表示確認後にお支払いウィジェットを表示する
              showWalletWidget(orderReferenceId);
          },
          onAddressSelect: function (orderReference) {
          },
          design: {
              designMode: 'responsive'
          },
          onError: function (error) {
              // エラー処理 
              // @see https://payments.amazon.com/documentation/lpwa/201954960
              console.log('OffAmazonPayments.Widgets.AddressBook', error.getErrorCode(), error.getErrorMessage());
          }
        }).bind("addressBookWidgetDiv");
    }

    function showWalletWidget(orderReferenceId) {
        new OffAmazonPayments.Widgets.Wallet({
          sellerId: '---mysellerid---',
          amazonOrderReferenceId: orderReferenceId,
          onReady: function(orderReference) {
              console.log(orderReference.getAmazonOrderReferenceId());
              //★ 決済ページ渡すorderReferenceIdを設定
              document.getElementById("orderReferenceId").value = orderReferenceId;
          },
          onPaymentSelect: function() {
              console.log(arguments);
          },
          design: {
              designMode: 'responsive'
          },
          onError: function(error) {
              // エラー処理 
              // @see https://payments.amazon.com/documentation/lpwa/201954960
              console.log('OffAmazonPayments.Widgets.Wallet', error.getErrorCode(), error.getErrorMessage());
          }
        }).bind("walletWidgetDiv");
    }
</script>
<script>
    window.onAmazonLoginReady = function() {
        amazon.Login.setClientId(---myClientId---');
    };
</script>
<script
    async='async' type='text/javascript' src='https://static-fe.payments-amazon.com/OffAmazonPayments/jp/lpa/js/Widgets.js'>
</script>
<form action="AmazonPay/azpayment4.php" method="POST">
    <input type="hidden" id="orderReferenceId" name="orderReferenceId">
    <input type="submit" value="購入する">
</form>
</body>
</html>


---The payment processing php is described below---
<?php
ini_set("display_errors", 1);
error_reporting(E_ALL);
//SDKの場所は環境により変更してください↓
require 'Client.php';
class Payment
{
    const MERCHANT_ID = '---mymerchantid---';
    const AMOUNT =30200; //決済額

    public function execute()
    {
        $referenceId = $_REQUEST['orderReferenceId'];

        // Clientインスタンスを作成
        $config = array(
            'merchant_id' => self::MERCHANT_ID,
            'access_key' => '---myaccesskey---',
            'secret_key' => '---mysecretkey---',
            'client_id' => '---myclientid---',
            'currency_code' => 'jpy',
            'region' => 'jp',);
        $client = new \ AmazonPay \ Client($config);

        // 注文情報をセット
        $setOrderParams = array(
            'merchant_id' => self::MERCHANT_ID,
            'amazon_order_reference_id' => $referenceId,
            'amount' => self::AMOUNT,
            'currency_code' => 'JPY',
            'seller_note' => 'ご購入ありがとうございます。
通常、ご入金後翌営業日以内には発送いたします。
在庫は十分用意しておりますが、注文の集中時、大量に注文された場合など、
万が一在庫不足により発送できない場合には、この限りではありませんが、
通常１週間以内には発送の手続きはさせていただいておりますので、
何卒ご了承くださいませ。
発送時にはeメールにてお知らせ致します。',
            'seller_order_id' => 'Order_' . time(),
            'store_name' => 'ハンドリフレクソロジー専門学院',
        );
        $client->SetOrderReferenceDetails($setOrderParams);

        if ($client->success === false) {
            header("Location:https://hand-school.com/paymenterror");
            exit;
        }

        // 注文情報を確定
        $confirmOrderParams = array(
            'amazon_order_reference_id' => $referenceId
        );
        $client->confirmOrderReference($confirmOrderParams);

        if ($client->success === false) {
            header("Location:https://hand-school.com/paymenterror");
            exit;
        }

        // オーソリをリクエスト
        $authorizeParams = array(
            'amazon_order_reference_id' => $referenceId,
            'authorization_amount' => self::AMOUNT,
            'authorization_reference_id' => 'Order_' . time(),
            'seller_authorization_note' => 'Authorizing payment',
            'transaction_timeout' => 0,
        );
        $response = $client->authorize($authorizeParams);
        $result = $response->toArray();

        $amazonAuthorizationId = $result['AuthorizeResult']['AuthorizationDetails']['AmazonAuthorizationId'];
        if (empty($amazonAuthorizationId)) {
            header("Location:https://hand-school.com/paymenterror");
            exit;
        }
        if ($client->success === false) {
            header("Location:https://hand-school.com/paymenterror");
            exit;
        }

        // 請求情報を確定
        $captureParams = array(
            'amazon_authorization_id' => $amazonAuthorizationId,
            'capture_amount' => self::AMOUNT,
            'currency_code' => 'JPY',
            'capture_reference_id' => 'Order_' . time(),
            'seller_capture_note' => '購入が完了しました。
',
        );
        $response = $client->capture($captureParams);
        $result = $response->toArray();

        // OrderReferenceを取得
        session_start();
        $token = $_SESSION['access_token'];
    $GetOrderReferenceDetailsParams = array(
            'amazon_order_reference_id' => $referenceId,
            'address_consent_token' =>  $token
        );
    $response = $client->GetOrderReferenceDetails($GetOrderReferenceDetailsParams);
        // 注文詳細、配送先情報等の取得
        // サンクスメールやDB登録等はこれを使用する
        $result = $response->toArray();

        // 注文の確定に失敗したらオーソリを取り消して、注文をクローズする
        if ($result['ResponseStatus'] !== '200') {
            $cancelParams = array(
                'merchant_id' => self::MERCHANT_ID,
                'amazon_order_reference_id' => $referenceId,
            );
            $client->cancelOrderReference($cancelParams);
            $closeParams = array(
                'merchant_id' => self::MERCHANT_ID,
                'amazon_authorization_id' => $amazonAuthorizationId,
            );
            $client->closeAuthorization($closeParams);

            header("Location:https://hand-school.com/addresserror");
            exit;
        }
		
        header("Location:https://hand-school.com/thanks.html");

        exit;
    }
}

$payment = new Payment();
$payment->execute();
?>

**Comment by SatoshiSakakibara** [comment]
Oh, I'm sorry I got in a strange shape. I do not understand the mechanism well.

**Comment by SatoshiSakakibara** [comment]
Thank you!
I was able to solve the problem.

The cause was that the specification of the sandbox parameter was missing when creating the Client instance.

Sir, Mr. Guillot , Thanks for your tips!
