### ISSUE TITLE
synchronous mode returns Pending

### ISSUE THREAD

**Issue by lotsofbytes** [amzn/amazon-pay-sdk-php#82]
In sandbox, calling the convenience "charge" method always returns "Pending" as AuthorizationStatus. 
I set "capture_now" as true, which means to use synchronous mode. 

According to the doc, 
"In synchronous mode, an Authorization object cannot be in the Pending state"

So, why returns "Pending"? Is it because of the sandbox?
I haven't tried with the live yet.

**Comment by islandskater43** [comment]
Hey @lotsofbytes - the `capture_now` parameter is used to determine if you want to automatically capture if the authorization is successful. To tell the API you want a synchronous response, pass `0` in to the `transaction_timeout` parameter.

**Comment by lotsofbytes** [comment]
@islandskater43 Thanks for the clear up.
