### ISSUE TITLE
order of using class methods to perform a transaction

### ISSUE THREAD

**Issue by pooria83** [amzn/amazon-pay-sdk-php#94]
Hi,
Can anyone tell me the order of using class methods to perform a transaction for standard payment and check the transaction result?

**Comment by shangamesh** [comment]
Hi, 
You can use following flow to place the order
- SetOrderReferenceDetails 
- ConfirmOrderReferenceDetails 
- Authorize 
- Capture

**Comment by pooria83** [comment]
> Hi, You can use following flow to place the order
> 
> * SetOrderReferenceDetails
> * ConfirmOrderReferenceDetails
> * Authorize
> * Capture
> 
> You can call GetOrderReferenceDetails API to get transaction result

thanks for replay.
would you please inform me how I can get 'amazon_order_reference_id' ?

**Comment by shangamesh** [comment]
Once Address Widget is rendered in website, you will have a function in JS code (orderReference.getAmazonOrderReferenceId()) to get Order Reference ID.

For more details, please refer : https://amazonpaylegacyintegrationguide.s3.amazonaws.com/docs/amazon-pay-onetime/add-widgets.html#addressbook-widget
