### ISSUE TITLE
str_contains issue

### ISSUE THREAD

**Issue by alberto-segura** [amzn/amazon-pay-sdk-php#97]
There is an issue on **amzn/amazon-payments-magento-2-plugin:dev-V2checkout-1.2.x**

vendor/amzn/amazon-payments-magento-2-plugin/src/PayV2/Plugin/PaymentTransactionIdUpdate.php:39

`if (str_contains($paymentMethodTitle, 'Amazon Pay') && $type == Transaction::TYPE_VOID) {`

The package states that it's compatible with php7.1, php7.2 and php7.3, however **str_contains** is only available on PHP8.

If anyone else is having issues, you can use the polyfill on the php documentation or you can just rewrite the function as STR_POS

`if (strpos($paymentMethodTitle, 'Amazon Pay') !== FALSE && $type == Transaction::TYPE_VOID) {`

**Comment by jaybeckr** [comment]
Hi @alberto-segura - this project is for the SDK, the Magento module is over at https://github.com/amzn/amazon-payments-magento-2-plugin/

That said, this issue has been addressed in current releases of the module, please upgrade to the Marketplace version of the module - https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html - and report on the amazon-payments-magento-2-plugin if you experience any other issues, thanks!

**Comment by islandskater43** [comment]
Closing issue. @alberto-segura - if you continue to experience any issues after following jaybeckr's advice, please open an issue in our [M2 repo](https://github.com/amzn/amazon-payments-magento-2-plugin/).
